"""first commit

Revision ID: d3f334ce3a4f
Revises: 
Create Date: 2025-07-03 16:43:11.527675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3f334ce3a4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_definition',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法生成的ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='实体类型名称，如user、product'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='显示名称，如用户、产品'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述信息'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统内置'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('meta', mysql.JSON(), nullable=True, comment='JSON格式的元数据，用于存储额外信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID（多租户支持）'),
    sa.PrimaryKeyConstraint('id'),
    comment='实体定义表'
    )
    op.create_index('idx_entity_def_enabled_tenant', 'entity_definition', ['is_enabled', 'tenant_id'], unique=False)
    op.create_index('idx_entity_def_name_tenant', 'entity_definition', ['name', 'tenant_id'], unique=False)
    op.create_index('idx_entity_def_system', 'entity_definition', ['is_system'], unique=False)
    op.create_table('entity_data',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法生成的ID'),
    sa.Column('entity_type_id', sa.BigInteger(), nullable=False, comment='实体类型ID'),
    sa.Column('data', mysql.JSON(), nullable=False, comment='JSON格式存储所有配置字段的值'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建者ID'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='最后更新者ID'),
    sa.Column('version', sa.BigInteger(), nullable=False, comment='版本号（用于乐观锁）'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', 'DELETED', name='entitystatus'), nullable=False, comment='状态'),
    sa.Column('meta', mysql.JSON(), nullable=True, comment='JSON格式的元数据，用于存储额外信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID（多租户支持）'),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='实体数据表'
    )
    op.create_index('idx_entity_data_created_at', 'entity_data', ['created_at'], unique=False)
    op.create_index('idx_entity_data_created_by', 'entity_data', ['created_by'], unique=False)
    op.create_index('idx_entity_data_status', 'entity_data', ['status'], unique=False)
    op.create_index('idx_entity_data_tenant', 'entity_data', ['tenant_id'], unique=False)
    op.create_index('idx_entity_data_type', 'entity_data', ['entity_type_id'], unique=False)
    op.create_index('idx_entity_data_type_status_tenant', 'entity_data', ['entity_type_id', 'status', 'tenant_id'], unique=False)
    op.create_index('idx_entity_data_type_tenant_created', 'entity_data', ['entity_type_id', 'tenant_id', 'created_at'], unique=False)
    op.create_index('idx_entity_data_version', 'entity_data', ['version'], unique=False)
    op.create_table('field_definition',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法生成的ID'),
    sa.Column('entity_type_id', sa.BigInteger(), nullable=False, comment='关联的实体类型ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='字段名称'),
    sa.Column('display_name', sa.String(length=200), nullable=False, comment='显示名称'),
    sa.Column('field_type', sa.Enum('STRING', 'NUMBER', 'BOOLEAN', 'DATE', 'DATETIME', 'ENUM', 'RELATION', 'ARRAY', 'JSON', 'TEXT', 'EMAIL', 'URL', 'FILE', 'IMAGE', 'PASSWORD', 'PHONE', 'ADDRESS', 'CURRENCY', 'PERCENT', name='fieldtype'), nullable=False, comment='字段类型(string/number/boolean/date/enum/relation等)'),
    sa.Column('value_type', sa.Enum('SINGLE', 'MULTIPLE', 'SINGLE_SELECT', 'MULTI_SELECT', 'CHECKBOX', 'RADIO', 'SWITCH', 'SLIDER', 'CASCADER', 'TREE_SELECT', 'TAG_INPUT', 'RICH_TEXT', 'CODE', 'COLOR', 'UPLOAD', 'RATING', name='valuetype'), nullable=False, comment='值类型(single/multiple/single_select/multi_select等)'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='是否必填'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否系统字段'),
    sa.Column('validation_rules', mysql.JSON(), nullable=True, comment='JSON格式的验证规则'),
    sa.Column('data_source', mysql.JSON(), nullable=True, comment='数据源设置（适用于下拉选择等）'),
    sa.Column('sort_order', sa.BigInteger(), nullable=False, comment='排序顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False, comment='租户ID（多租户支持）'),
    sa.ForeignKeyConstraint(['entity_type_id'], ['entity_definition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='字段定义表'
    )
    op.create_index('idx_field_def_entity_type', 'field_definition', ['entity_type_id'], unique=False)
    op.create_index('idx_field_def_name_entity', 'field_definition', ['name', 'entity_type_id'], unique=False)
    op.create_index('idx_field_def_required', 'field_definition', ['is_required'], unique=False)
    op.create_index('idx_field_def_system', 'field_definition', ['is_system'], unique=False)
    op.create_index('idx_field_def_tenant', 'field_definition', ['tenant_id'], unique=False)
    op.create_index('idx_field_def_type', 'field_definition', ['field_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_field_def_type', table_name='field_definition')
    op.drop_index('idx_field_def_tenant', table_name='field_definition')
    op.drop_index('idx_field_def_system', table_name='field_definition')
    op.drop_index('idx_field_def_required', table_name='field_definition')
    op.drop_index('idx_field_def_name_entity', table_name='field_definition')
    op.drop_index('idx_field_def_entity_type', table_name='field_definition')
    op.drop_table('field_definition')
    op.drop_index('idx_entity_data_version', table_name='entity_data')
    op.drop_index('idx_entity_data_type_tenant_created', table_name='entity_data')
    op.drop_index('idx_entity_data_type_status_tenant', table_name='entity_data')
    op.drop_index('idx_entity_data_type', table_name='entity_data')
    op.drop_index('idx_entity_data_tenant', table_name='entity_data')
    op.drop_index('idx_entity_data_status', table_name='entity_data')
    op.drop_index('idx_entity_data_created_by', table_name='entity_data')
    op.drop_index('idx_entity_data_created_at', table_name='entity_data')
    op.drop_table('entity_data')
    op.drop_index('idx_entity_def_system', table_name='entity_definition')
    op.drop_index('idx_entity_def_name_tenant', table_name='entity_definition')
    op.drop_index('idx_entity_def_enabled_tenant', table_name='entity_definition')
    op.drop_table('entity_definition')
    # ### end Alembic commands ###
