"""2 commit

Revision ID: d8e2cba32c3c
Revises: d3f334ce3a4f
Create Date: 2025-07-04 09:46:02.827868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e2cba32c3c'
down_revision: Union[str, Sequence[str], None] = 'd3f334ce3a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_data', sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父实体ID（用于树形结构）'))
    op.create_foreign_key(None, 'entity_data', 'entity_data', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('entity_definition', sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父实体ID（用于树形结构）'))
    op.create_foreign_key(None, 'entity_definition', 'entity_definition', ['parent_id'], ['id'], ondelete='SET NULL')
    op.add_column('field_definition', sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父字段ID（用于分组或层级）'))
    op.create_foreign_key(None, 'field_definition', 'field_definition', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field_definition', type_='foreignkey')
    op.drop_column('field_definition', 'parent_id')
    op.drop_constraint(None, 'entity_definition', type_='foreignkey')
    op.drop_column('entity_definition', 'parent_id')
    op.drop_constraint(None, 'entity_data', type_='foreignkey')
    op.drop_column('entity_data', 'parent_id')
    # ### end Alembic commands ###
